### Cadastrar Produto
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "Pizza",
    "Preco": 2.30
}

### Listar Produto
GET  https://localhost:5001/api/produto/list

### Buscar produto pelo ID
GET  https://localhost:5001/api/produto/getbyid/2

# ### Alterar produto
# PUT  https://localhost:5001/api/produto/update/2

### Deletar produto
DELETE https://localhost:5001/api/produto/delete/Bolacha